client/src/components/FadeInContainer/index.css, client/src/components/FadeInContainer/index.js, client/src/components/FadeInContainer/index.scss, client/src/components/HideOnClickOutsideContainer/index.js, client/src/components/Notifications/index.css, client/src/components/Notifications/index.js, client/src/components/Notifications/index.scss, client/src/components/ProfileMenu/index.css, client/src/components/ProfileMenu/index.js, client/src/components/ProfileMenu/index.scss, client/src/layout/header/index.css, client/src/layout/header/index.js, client/src/layout/header/index.scss
Added popup with notifications.
=> Add notifications popup

client/package-lock.json, client/package.json, client/src/App.css, client/src/App.js, client/src/App.scss, client/src/layout/header/index.js, client/src/pages/RolesList/index.css, client/src/pages/RolesList/index.js, client/src/pages/RolesList/index.scss, client/src/pages/RolesList/roles.js, client/src/pages/UsersList/index.css, client/src/pages/UsersList/index.scss, client/src/utils/validateForm.js
=> Add roles list

client/src/components/ConfirmTag/index.css, client/src/components/ConfirmTag/index.scss, client/src/pages/UsersList/index.css, client/src/pages/UsersList/index.scss
Updated 'yes' and 'no' labels on users list page.
=> Update 'yes' and 'no' labels on users list page

client/package-lock.json, client/src/pages/UsersList/index.js
=> Restore edit user form

client/src/pages/RolesList/index.js
Commented out the Filter Header on the Role Page.
=> Removed filter from roles header

client/src/App.js, client/src/layout/header/index.js, client/src/pages/TenantsList/index.js, client/src/pages/TenantsList/index.scss, client/src/pages/TenantsList/tenants.js
I copied the roles page layout and added columns. I put some placeholder buttons, but the button rendering could use some refactoring. I was also trying to get the Font Awesome icons to display for the buttons, but apparently there was a known issue with Prime React overloading the styling, and keeping the icons from displaying. That might be able to be fixed with some CSS.
=> Iss14 tenant

client/package-lock.json, client/package.json, client/src/components/Checkbox/index.css, client/src/components/Checkbox/index.scss, client/src/components/Tree/index.js, client/src/components/Tree/index.scss, client/src/pages/RolesList/components/Form/index.js, client/src/pages/RolesList/components/Form/index.scss, client/src/pages/RolesList/index.js, client/src/pages/UsersList/components/Form/index.js
Added edit role form. Issue https://github.com/joewalling/ReactAdvantage/issues/13.
=> Add edit role form

client/src/pages/RolesList/index.js
Fix https://github.com/joewalling/ReactAdvantage/issues/42.
=> Reduce space at top of roles

client/src/pages/TenantsList/components/Form/index.js, client/src/pages/TenantsList/components/Form/index.scss, client/src/pages/TenantsList/index.js, client/src/pages/TenantsList/index.scss, client/src/pages/UsersList/components/Form/index.js
Fix https://github.com/joewalling/ReactAdvantage/issues/15. Added tenant form.
=> Add tenant form

client/package-lock.json, client/package.json, client/src/components/SearchQuery/index.css, client/src/components/SearchQuery/index.js, client/src/components/SearchQuery/index.scss, client/src/pages/UsersList/index.js
Added updated query builder https://github.com/joewalling/ReactAdvantage/issues/22. You can test it on users page ("Date" filter).
=> Add updated query builder

client/package-lock.json, client/src/components/SearchQuery/index.js
Added new rules and updated old ones in react-two-way-querybuilder.
=> Add new rules to react-two-way-querybuilder

client/src/components/UserSettings/index.js, client/src/components/UserSettings/index.scss
=> fix: adjust user image select layout

client/src/pages/UsersList/components/Form/index.js, client/src/pages/UsersList/components/Form/index.scss
=> fix: add user layout

client/src/pages/RolesList/components/Form/index.js, client/src/pages/RolesList/components/Form/index.scss
=> fix: role permissions tree style

client/src/components/Button/index.js, client/src/components/UserSettings/index.js
=> fix: button styles

client/src/components/Notifications/index.scss
=> fix: reduce notification popup width

client/src/layout/container/index.scss, client/src/layout/header/index.scss
=> fix: avatar box zoom

client/src/pages/UsersList/components/Form/index.js
=> fix: add user button text

client/src/components/Checkbox/index.scss
=> fix: add margin between checkbox and label

client/src/pages/RolesList/index.js
Hide the actions column on exported CSV file
=> Hide the actions column on exported CSV file
